name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - uses: fregante/daily-version-action@a1fc2b591c0bee1c12274b8dffaddea11c079082
        # TODO: 最新版ではタグがないときのエラー処理がまた抜けてるので一旦コミットで指定
        name: Create tag if necessary
        id: daily-version
      - run: npm run build
      - name: Update manifest.json
        run: |
          npx dot-json@1 dist/manifest.json version ${{ steps.daily-version.outputs.version }}
      - run: node deploy.js
      - name: Submit
        run: |
          npx chrome-webstore-upload-cli@2 upload --source extension.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.daily-version.outputs.version }}
          draft: false
          generate_release_notes: true
          files: extension.zip
